version: '4.15.0'
services:
  prob_2_notebook_image:
    build:
      context: .
      target: prob_2_notebook_image
    ports: 
    - "127.0.0.1:8888:8888"
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    volumes:
    - type: bind
      source: ./docker_mount
      target: /tmp

  prob_3_image:
    build:
      context: .
      target: prob_3_image